management:
    security:
        enabled: false
server:
    port: 8092
eureka:         #tells about the Eureka server details and its refresh time
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
        hostname: CGI-shubham
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8091/eureka/
        healthcheck:
            enabled: true
        lease:
            duration: 5
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ska662/centralrepo.git

    application:
      name: config-server
